/**
 * The Move Score email layout, shared by every email we send: our own messages
 * (src/lib/messaging/render.ts, sent through Resend) and the Supabase Auth
 * templates (generated by scripts/email/build-auth-templates.ts). Pure module:
 * no Node, browser or Next.js APIs (the admin composer renders it in the browser).
 *
 * Mail-client rules followed here: tables for layout, inline styles on every
 * element (Gmail drops classes in some views), a <style> block only for dark mode
 * and small screens, images hosted on the live site with width/height/alt set, a
 * button made of a coloured table cell (no VML, so nothing breaks when a template
 * engine strips comments), and a hidden preheader.
 */
import { APP_PAGE_URL, SITE_URL } from "../site";

export const EMAIL_BRAND = {
  product: "Move Score",
  productUrl: APP_PAGE_URL,
  maker: "Move Beyond",
  makerUrl: "https://mbeg.org",
  contact: "info@mbeg.org",
  privacyUrl: `${APP_PAGE_URL}/privacy`,
  /** Hosted logos: public/email/ in this repo, served by the live site. */
  assetBase: `${SITE_URL}/email`,
  legal: "© Move Beyond. All rights reserved.",
} as const;

export const EMAIL_COLORS = {
  navy: "#01041A",
  ink: "#00000B",
  ball: "#FCFC00",
  stage: "#1E6BFF",
  page: "#EDEFF5",
  card: "#FFFFFF",
  text: "#0B0E1F",
  muted: "#5A6178",
  rule: "#E1E4EE",
  // Dark mode
  darkCard: "#0A0F2A",
  darkText: "#E8EBF5",
  darkMuted: "#9AA3BD",
  darkRule: "#1D2447",
} as const;

const DISPLAY_FONT = "'Archivo Expanded','Archivo','Arial Black','Helvetica Neue',Helvetica,Arial,sans-serif";
const BODY_FONT = "-apple-system,BlinkMacSystemFont,'Segoe UI',Helvetica,Arial,sans-serif";
const MONO_FONT = "'SF Mono',Menlo,Consolas,'Courier New',monospace";

export function escapeHtml(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
}

const C = EMAIL_COLORS;
const P_STYLE = `margin:0 0 16px;font-family:${BODY_FONT};font-size:16px;line-height:1.55;color:${C.text};`;
const LINK_STYLE = `color:${C.stage};text-decoration:underline;`;

/** Escaped text with links made clickable and line breaks kept, one <p> per paragraph. */
export function textToHtml(text: string): string {
  const escaped = escapeHtml(text);
  const linked = escaped.replace(/\bhttps?:\/\/[^\s<]+[^\s<.,;:!?)]/g, (url) => `<a href="${url}" class="ms-link" style="${LINK_STYLE}">${url}</a>`);
  return linked
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter(Boolean)
    .map((p) => `<p class="ms-text" style="${P_STYLE}">${p.replace(/\n/g, "<br>")}</p>`)
    .join("\n");
}

export interface BrandedEmailInput {
  /** The <title> (and usually the subject). Plain text. */
  title: string;
  /** Big heading at the top of the card. Plain text; defaults to `title`. */
  heading?: string;
  /** Inbox preview line. Plain text; defaults to the start of `body`. */
  preheader?: string;
  /** The message. Plain text: blank lines split paragraphs, URLs become links. */
  body: string;
  /** A code in its own box (player codes, one-time codes). */
  code?: { label?: string; value: string } | null;
  /** The main action. */
  button?: { label: string; url: string } | null;
  /** Show "Button not working? Paste this link" under the button. */
  linkFallback?: boolean;
  /** Put the code box after the button (the code is the fallback, not the point). */
  codeAfterButton?: boolean;
  /** Small print under the message ("If you didn't ask for this…"). Plain text. */
  note?: string | null;
  /** Why the person gets this email, in the footer. Plain text. */
  reason?: string | null;
}

export interface BrandedEmail {
  html: string;
  text: string;
}

const PREHEADER_PAD = "&#847;&zwnj;&nbsp;".repeat(40);

function preheaderOf(input: BrandedEmailInput): string {
  if (input.preheader != null) return input.preheader;
  const flat = input.body.replace(/\s+/g, " ").trim();
  return flat.length > 110 ? `${flat.slice(0, 107).trimEnd()}…` : flat;
}

const DARK_CSS = `
:root{color-scheme:light dark;supported-color-schemes:light dark;}
body{margin:0;padding:0;width:100%!important;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;}
table{border-collapse:collapse;mso-table-lspace:0;mso-table-rspace:0;}
img{border:0;outline:none;text-decoration:none;-ms-interpolation-mode:bicubic;}
a[x-apple-data-detectors]{color:inherit!important;text-decoration:none!important;}
@media (max-width:620px){
  .ms-pad{padding-left:22px!important;padding-right:22px!important;}
  .ms-h1{font-size:23px!important;}
  .ms-code{font-size:26px!important;letter-spacing:4px!important;}
}
@media (prefers-color-scheme:dark){
  .ms-bg{background:${C.ink}!important;}
  .ms-card{background:${C.darkCard}!important;}
  .ms-text{color:${C.darkText}!important;}
  .ms-muted{color:${C.darkMuted}!important;}
  .ms-rule{border-color:${C.darkRule}!important;}
  .ms-link{color:${C.ball}!important;}
}
[data-ogsc] .ms-bg{background:${C.ink}!important;}
[data-ogsc] .ms-card{background:${C.darkCard}!important;}
[data-ogsc] .ms-text{color:${C.darkText}!important;}
[data-ogsc] .ms-muted{color:${C.darkMuted}!important;}
[data-ogsc] .ms-link{color:${C.ball}!important;}
`.trim();

function buttonHtml(b: { label: string; url: string }): string {
  const href = escapeHtml(b.url);
  return `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="margin:8px 0 8px;">
<tr><td align="center" bgcolor="${C.stage}" style="background:${C.stage};border-radius:12px;">
<a href="${href}" target="_blank" style="display:inline-block;padding:15px 30px;font-family:${DISPLAY_FONT};font-size:15px;font-weight:800;letter-spacing:0.5px;line-height:1.2;color:#FFFFFF;text-decoration:none;border-radius:12px;border:1px solid ${C.stage};">${escapeHtml(b.label)}</a>
</td></tr>
</table>`;
}

function codeHtml(c: { label?: string; value: string }, after = false): string {
  return `<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="margin:${after ? "24px 0 4px" : "8px 0 20px"};">
<tr><td align="center" bgcolor="${C.navy}" style="background:${C.navy};border-radius:14px;padding:18px 16px 20px;">
<div style="font-family:${BODY_FONT};font-size:11px;font-weight:700;letter-spacing:2px;text-transform:uppercase;color:#9AA3BD;margin:0 0 8px;">${escapeHtml(c.label ?? "Your code")}</div>
<div class="ms-code" style="font-family:${MONO_FONT};font-size:32px;font-weight:700;letter-spacing:6px;line-height:1.2;color:${C.ball};">${escapeHtml(c.value)}</div>
</td></tr>
</table>`;
}

function footerHtml(reason: string | null | undefined): string {
  const B = EMAIL_BRAND;
  const small = `font-family:${BODY_FONT};font-size:12px;line-height:1.6;color:${C.muted};`;
  const flink = `color:${C.muted};text-decoration:underline;`;
  return `<tr><td class="ms-pad ms-rule" style="padding:22px 36px 28px;border-top:1px solid ${C.rule};">
<table role="presentation" cellpadding="0" cellspacing="0" border="0">
<tr>
<td valign="middle" style="padding:0 12px 0 0;"><img src="${B.assetBase}/move-score-icon-96.png" width="40" height="40" alt="" style="display:block;width:40px;height:40px;border-radius:10px;"></td>
<td valign="middle" class="ms-text" style="font-family:${BODY_FONT};font-size:14px;line-height:1.45;color:${C.text};"><strong>${B.product}</strong> is made by <a href="${B.makerUrl}" class="ms-link" style="${LINK_STYLE}font-weight:700;">${B.maker}</a><br><span class="ms-muted" style="${small}">Questions? Write to <a href="mailto:${B.contact}" class="ms-link" style="${LINK_STYLE}">${B.contact}</a></span></td>
</tr>
</table>
${reason ? `<p class="ms-muted" style="margin:16px 0 0;${small}">${escapeHtml(reason)}</p>` : ""}
<p class="ms-muted" style="margin:12px 0 0;${small}"><a href="${B.privacyUrl}" class="ms-muted" style="${flink}">Privacy</a> &nbsp;·&nbsp; <a href="${B.makerUrl}" class="ms-muted" style="${flink}">mbeg.org</a><br>${escapeHtml(B.legal)}</p>
</td></tr>`;
}

/** The full HTML document for one email. */
export function brandedEmailHtml(input: BrandedEmailInput): string {
  const B = EMAIL_BRAND;
  const heading = input.heading ?? input.title;
  const fallback =
    input.button && input.linkFallback
      ? `<p class="ms-muted" style="margin:14px 0 0;font-family:${BODY_FONT};font-size:13px;line-height:1.5;color:${C.muted};">Button not working? Copy this link into your browser:<br><a href="${escapeHtml(input.button.url)}" class="ms-link" style="${LINK_STYLE}word-break:break-all;">${escapeHtml(input.button.url)}</a></p>`
      : "";
  const note = input.note
    ? `<p class="ms-muted" style="margin:22px 0 0;font-family:${BODY_FONT};font-size:13px;line-height:1.5;color:${C.muted};">${escapeHtml(input.note)}</p>`
    : "";

  return `<!doctype html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="x-apple-disable-message-reformatting">
<meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no">
<meta name="color-scheme" content="light dark">
<meta name="supported-color-schemes" content="light dark">
<title>${escapeHtml(input.title)}</title>
<style>
${DARK_CSS}
</style>
</head>
<body class="ms-bg" style="margin:0;padding:0;background:${C.page};">
<div style="display:none;max-height:0;max-width:0;overflow:hidden;opacity:0;mso-hide:all;font-size:1px;line-height:1px;color:${C.page};">${escapeHtml(preheaderOf(input))}${PREHEADER_PAD}</div>
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" class="ms-bg" bgcolor="${C.page}" style="background:${C.page};">
<tr><td align="center" style="padding:28px 12px;">
<!--[if mso]><table role="presentation" width="600" cellpadding="0" cellspacing="0" border="0"><tr><td><![endif]-->
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" class="ms-card" bgcolor="${C.card}" style="width:100%;max-width:600px;background:${C.card};border-radius:18px;overflow:hidden;">
<tr><td bgcolor="${C.navy}" style="background:${C.navy};padding:26px 36px 24px;" class="ms-pad">
<a href="${B.productUrl}" style="text-decoration:none;"><img src="${B.assetBase}/move-score-lockup@2x.png" width="240" height="46" alt="${B.product}" style="display:block;width:240px;height:auto;max-width:100%;border:0;color:#FFFFFF;font-family:${DISPLAY_FONT};font-size:22px;font-weight:900;"></a>
</td></tr>
<tr><td bgcolor="${C.ball}" style="background:${C.ball};height:4px;line-height:4px;font-size:4px;">&nbsp;</td></tr>
<tr><td class="ms-pad" style="padding:34px 36px 30px;">
<h1 class="ms-text ms-h1" style="margin:0 0 20px;font-family:${DISPLAY_FONT};font-size:26px;font-weight:900;line-height:1.2;letter-spacing:-0.2px;color:${C.text};">${escapeHtml(heading)}</h1>
${textToHtml(input.body)}
${input.code && !input.codeAfterButton ? codeHtml(input.code) : ""}
${input.button ? buttonHtml(input.button) : ""}
${fallback}
${input.code && input.codeAfterButton ? codeHtml(input.code, true) : ""}
${note}
</td></tr>
${footerHtml(input.reason)}
</table>
<!--[if mso]></td></tr></table><![endif]-->
</td></tr>
</table>
</body>
</html>
`;
}

/** The plain-text part: the same message, the code, the link, and the signature. */
export function brandedEmailText(input: BrandedEmailInput): string {
  const B = EMAIL_BRAND;
  const blocks = [
    input.heading ?? input.title,
    input.body.trim(),
    input.code && !input.codeAfterButton ? `${input.code.label ?? "Your code"}: ${input.code.value}` : "",
    input.button ? `${input.button.label}: ${input.button.url}` : "",
    input.code && input.codeAfterButton ? `${input.code.label ?? "Your code"}: ${input.code.value}` : "",
    input.note ?? "",
    [
      "—",
      `${B.product} is made by ${B.maker} · ${B.makerUrl}`,
      `Questions? Write to ${B.contact}`,
      input.reason ?? "",
      `Privacy: ${B.privacyUrl}`,
      B.legal,
    ]
      .filter(Boolean)
      .join("\n"),
  ];
  return blocks.filter((b) => b.trim() !== "").join("\n\n");
}

export function brandedEmail(input: BrandedEmailInput): BrandedEmail {
  return { html: brandedEmailHtml(input), text: brandedEmailText(input) };
}
